server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: rms-auth
          uri: lb://rms-auth
          predicates:
            - Path=/rms-auth/**
          filters:
            - StripPrefix=1
        - id: rms-admin
          uri: lb://rms-admin
          predicates:
            - Path=/rms-admin/**
          filters:
            - StripPrefix=1
        - id: rms-portal
          uri: lb://rms-portal
          predicates:
            - Path=/rms-portal/**
          filters:
            - StripPrefix=1
        - id: rms-search
          uri: lb://rms-search
          predicates:
            - Path=/rms-search/**
          filters:
            - StripPrefix=1
        - id: rms-demo
          uri: lb://rms-demo
          predicates:
            - Path=/rms-demo/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/rms-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/rms-auth/oauth/token"
      - "/rms-auth/rsa/publicKey"
      - "/rms-admin/admin/login"
      - "/rms-admin/admin/register"
      - "/rms-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
