spring:
  datasource:
    url: jdbc:mysql://8.131.251.49:3306/rpa_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Root@123
  redis:
    host: 8.131.251.49 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Root@123 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
logging:
  level:
    root: info
    com.ey.rms: debug
logstash:
  host: localhost